# Generated by Django 5.1.5 on 2025-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MFD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='use_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
