# Generated by Django 5.1.5 on 2025-03-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_mfd_product_use_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Item', models.CharField(max_length=255)),
                ('Calories', models.FloatField()),
                ('Protein', models.FloatField()),
                ('Carbohydrates', models.FloatField()),
                ('Fiber', models.FloatField()),
                ('Sugars', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
